<?php
/**
 * ConfirmMode
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;
use \SmartCat\ObjectSerializer;

/**
 * ConfirmMode Class Doc Comment
 *
 * @category Class
 * @description Mode of segment confirmation at file upload
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConfirmMode
{
    /**
     * Possible values of this enum
     */
    public const NONE = 'None';

    public const BY_STATES = 'ByStates';

    public const AT_FIRST_STAGE = 'AtFirstStage';

    public const AT_LAST_STAGE = 'AtLastStage';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::BY_STATES,
            self::AT_FIRST_STAGE,
            self::AT_LAST_STAGE
        ];
    }
}


