<?php
/**
 * ExportingSegmentCompletionState
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;
use \SmartCat\ObjectSerializer;

/**
 * ExportingSegmentCompletionState Class Doc Comment
 *
 * @category Class
 * @description Minimal exporting segment completion state.  Specifies the state in which any key (segment) must be in order to be exported.
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ExportingSegmentCompletionState
{
    /**
     * Possible values of this enum
     */
    public const DRAFT = 'draft';

    public const INTERMEDIATE = 'intermediate';

    public const _FINAL = 'final';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DRAFT,
            self::INTERMEDIATE,
            self::_FINAL
        ];
    }
}


