<?php
/**
 * ProjectModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;

use \ArrayAccess;
use \SmartCat\ObjectSerializer;

/**
 * ProjectModel Class Doc Comment
 *
 * @category Class
 * @description Project model
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ProjectModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ProjectModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'accountId' => 'string',
        'name' => 'string',
        'description' => 'string',
        'deadline' => '\DateTime',
        'creationDate' => '\DateTime',
        'createdByUserId' => 'string',
        'createdByUserEmail' => 'string',
        'modificationDate' => '\DateTime',
        'sourceLanguageId' => 'int',
        'sourceLanguage' => 'string',
        'targetLanguages' => 'string[]',
        'status' => '\SmartCat\Model\ContractsProjectStatus',
        'statusModificationDate' => '\DateTime',
        'domainId' => 'int',
        'clientId' => 'string',
        'vendors' => '\SmartCat\Model\ProjectVendorModel[]',
        'workflowStages' => '\SmartCat\Model\ProjectWorkflowStageModel[]',
        'documents' => '\SmartCat\Model\DocumentModel[]',
        'externalTag' => 'string',
        'specializations' => '\SmartCat\Model\Specialization[]',
        'managers' => 'string[]',
        'number' => 'string',
        'customFields' => 'array<string,string>'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'accountId' => 'uuid',
        'name' => null,
        'description' => null,
        'deadline' => 'date-time',
        'creationDate' => 'date-time',
        'createdByUserId' => 'uuid',
        'createdByUserEmail' => null,
        'modificationDate' => 'date-time',
        'sourceLanguageId' => 'int32',
        'sourceLanguage' => null,
        'targetLanguages' => null,
        'status' => null,
        'statusModificationDate' => 'date-time',
        'domainId' => 'int32',
        'clientId' => 'uuid',
        'vendors' => null,
        'workflowStages' => null,
        'documents' => null,
        'externalTag' => null,
        'specializations' => null,
        'managers' => null,
        'number' => null,
        'customFields' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
		'accountId' => false,
		'name' => true,
		'description' => true,
		'deadline' => true,
		'creationDate' => false,
		'createdByUserId' => true,
		'createdByUserEmail' => true,
		'modificationDate' => false,
		'sourceLanguageId' => false,
		'sourceLanguage' => true,
		'targetLanguages' => true,
		'status' => false,
		'statusModificationDate' => true,
		'domainId' => true,
		'clientId' => true,
		'vendors' => true,
		'workflowStages' => true,
		'documents' => true,
		'externalTag' => true,
		'specializations' => true,
		'managers' => true,
		'number' => true,
		'customFields' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'accountId' => 'accountId',
        'name' => 'name',
        'description' => 'description',
        'deadline' => 'deadline',
        'creationDate' => 'creationDate',
        'createdByUserId' => 'createdByUserId',
        'createdByUserEmail' => 'createdByUserEmail',
        'modificationDate' => 'modificationDate',
        'sourceLanguageId' => 'sourceLanguageId',
        'sourceLanguage' => 'sourceLanguage',
        'targetLanguages' => 'targetLanguages',
        'status' => 'status',
        'statusModificationDate' => 'statusModificationDate',
        'domainId' => 'domainId',
        'clientId' => 'clientId',
        'vendors' => 'vendors',
        'workflowStages' => 'workflowStages',
        'documents' => 'documents',
        'externalTag' => 'externalTag',
        'specializations' => 'specializations',
        'managers' => 'managers',
        'number' => 'number',
        'customFields' => 'customFields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'accountId' => 'setAccountId',
        'name' => 'setName',
        'description' => 'setDescription',
        'deadline' => 'setDeadline',
        'creationDate' => 'setCreationDate',
        'createdByUserId' => 'setCreatedByUserId',
        'createdByUserEmail' => 'setCreatedByUserEmail',
        'modificationDate' => 'setModificationDate',
        'sourceLanguageId' => 'setSourceLanguageId',
        'sourceLanguage' => 'setSourceLanguage',
        'targetLanguages' => 'setTargetLanguages',
        'status' => 'setStatus',
        'statusModificationDate' => 'setStatusModificationDate',
        'domainId' => 'setDomainId',
        'clientId' => 'setClientId',
        'vendors' => 'setVendors',
        'workflowStages' => 'setWorkflowStages',
        'documents' => 'setDocuments',
        'externalTag' => 'setExternalTag',
        'specializations' => 'setSpecializations',
        'managers' => 'setManagers',
        'number' => 'setNumber',
        'customFields' => 'setCustomFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'accountId' => 'getAccountId',
        'name' => 'getName',
        'description' => 'getDescription',
        'deadline' => 'getDeadline',
        'creationDate' => 'getCreationDate',
        'createdByUserId' => 'getCreatedByUserId',
        'createdByUserEmail' => 'getCreatedByUserEmail',
        'modificationDate' => 'getModificationDate',
        'sourceLanguageId' => 'getSourceLanguageId',
        'sourceLanguage' => 'getSourceLanguage',
        'targetLanguages' => 'getTargetLanguages',
        'status' => 'getStatus',
        'statusModificationDate' => 'getStatusModificationDate',
        'domainId' => 'getDomainId',
        'clientId' => 'getClientId',
        'vendors' => 'getVendors',
        'workflowStages' => 'getWorkflowStages',
        'documents' => 'getDocuments',
        'externalTag' => 'getExternalTag',
        'specializations' => 'getSpecializations',
        'managers' => 'getManagers',
        'number' => 'getNumber',
        'customFields' => 'getCustomFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('accountId', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('deadline', $data ?? [], null);
        $this->setIfExists('creationDate', $data ?? [], null);
        $this->setIfExists('createdByUserId', $data ?? [], null);
        $this->setIfExists('createdByUserEmail', $data ?? [], null);
        $this->setIfExists('modificationDate', $data ?? [], null);
        $this->setIfExists('sourceLanguageId', $data ?? [], null);
        $this->setIfExists('sourceLanguage', $data ?? [], null);
        $this->setIfExists('targetLanguages', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('statusModificationDate', $data ?? [], null);
        $this->setIfExists('domainId', $data ?? [], null);
        $this->setIfExists('clientId', $data ?? [], null);
        $this->setIfExists('vendors', $data ?? [], null);
        $this->setIfExists('workflowStages', $data ?? [], null);
        $this->setIfExists('documents', $data ?? [], null);
        $this->setIfExists('externalTag', $data ?? [], null);
        $this->setIfExists('specializations', $data ?? [], null);
        $this->setIfExists('managers', $data ?? [], null);
        $this->setIfExists('number', $data ?? [], null);
        $this->setIfExists('customFields', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id Project ID
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets accountId
     *
     * @return string|null
     */
    public function getAccountId()
    {
        return $this->container['accountId'];
    }

    /**
     * Sets accountId
     *
     * @param string|null $accountId Account ID
     *
     * @return self
     */
    public function setAccountId($accountId)
    {
        if (is_null($accountId)) {
            throw new \InvalidArgumentException('non-nullable accountId cannot be null');
        }
        $this->container['accountId'] = $accountId;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Project name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description Project description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets deadline
     *
     * @return \DateTime|null
     */
    public function getDeadline()
    {
        return $this->container['deadline'];
    }

    /**
     * Sets deadline
     *
     * @param \DateTime|null $deadline Project deadline
     *
     * @return self
     */
    public function setDeadline($deadline)
    {
        if (is_null($deadline)) {
            array_push($this->openAPINullablesSetToNull, 'deadline');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deadline', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deadline'] = $deadline;

        return $this;
    }

    /**
     * Gets creationDate
     *
     * @return \DateTime|null
     */
    public function getCreationDate()
    {
        return $this->container['creationDate'];
    }

    /**
     * Sets creationDate
     *
     * @param \DateTime|null $creationDate Creation date
     *
     * @return self
     */
    public function setCreationDate($creationDate)
    {
        if (is_null($creationDate)) {
            throw new \InvalidArgumentException('non-nullable creationDate cannot be null');
        }
        $this->container['creationDate'] = $creationDate;

        return $this;
    }

    /**
     * Gets createdByUserId
     *
     * @return string|null
     */
    public function getCreatedByUserId()
    {
        return $this->container['createdByUserId'];
    }

    /**
     * Sets createdByUserId
     *
     * @param string|null $createdByUserId User ID of the project creator
     *
     * @return self
     */
    public function setCreatedByUserId($createdByUserId)
    {
        if (is_null($createdByUserId)) {
            array_push($this->openAPINullablesSetToNull, 'createdByUserId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('createdByUserId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['createdByUserId'] = $createdByUserId;

        return $this;
    }

    /**
     * Gets createdByUserEmail
     *
     * @return string|null
     */
    public function getCreatedByUserEmail()
    {
        return $this->container['createdByUserEmail'];
    }

    /**
     * Sets createdByUserEmail
     *
     * @param string|null $createdByUserEmail Email of the project creator
     *
     * @return self
     */
    public function setCreatedByUserEmail($createdByUserEmail)
    {
        if (is_null($createdByUserEmail)) {
            array_push($this->openAPINullablesSetToNull, 'createdByUserEmail');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('createdByUserEmail', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['createdByUserEmail'] = $createdByUserEmail;

        return $this;
    }

    /**
     * Gets modificationDate
     *
     * @return \DateTime|null
     */
    public function getModificationDate()
    {
        return $this->container['modificationDate'];
    }

    /**
     * Sets modificationDate
     *
     * @param \DateTime|null $modificationDate Last modification date
     *
     * @return self
     */
    public function setModificationDate($modificationDate)
    {
        if (is_null($modificationDate)) {
            throw new \InvalidArgumentException('non-nullable modificationDate cannot be null');
        }
        $this->container['modificationDate'] = $modificationDate;

        return $this;
    }

    /**
     * Gets sourceLanguageId
     *
     * @return int|null
     */
    public function getSourceLanguageId()
    {
        return $this->container['sourceLanguageId'];
    }

    /**
     * Sets sourceLanguageId
     *
     * @param int|null $sourceLanguageId Project source language code
     *
     * @return self
     */
    public function setSourceLanguageId($sourceLanguageId)
    {
        if (is_null($sourceLanguageId)) {
            throw new \InvalidArgumentException('non-nullable sourceLanguageId cannot be null');
        }
        $this->container['sourceLanguageId'] = $sourceLanguageId;

        return $this;
    }

    /**
     * Gets sourceLanguage
     *
     * @return string|null
     */
    public function getSourceLanguage()
    {
        return $this->container['sourceLanguage'];
    }

    /**
     * Sets sourceLanguage
     *
     * @param string|null $sourceLanguage Project source language
     *
     * @return self
     */
    public function setSourceLanguage($sourceLanguage)
    {
        if (is_null($sourceLanguage)) {
            array_push($this->openAPINullablesSetToNull, 'sourceLanguage');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sourceLanguage', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sourceLanguage'] = $sourceLanguage;

        return $this;
    }

    /**
     * Gets targetLanguages
     *
     * @return string[]|null
     */
    public function getTargetLanguages()
    {
        return $this->container['targetLanguages'];
    }

    /**
     * Sets targetLanguages
     *
     * @param string[]|null $targetLanguages Project target languages
     *
     * @return self
     */
    public function setTargetLanguages($targetLanguages)
    {
        if (is_null($targetLanguages)) {
            array_push($this->openAPINullablesSetToNull, 'targetLanguages');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('targetLanguages', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['targetLanguages'] = $targetLanguages;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \SmartCat\Model\ContractsProjectStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \SmartCat\Model\ContractsProjectStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets statusModificationDate
     *
     * @return \DateTime|null
     */
    public function getStatusModificationDate()
    {
        return $this->container['statusModificationDate'];
    }

    /**
     * Sets statusModificationDate
     *
     * @param \DateTime|null $statusModificationDate Last status change date (including the status of the OnApproval and CancelledBy attributes)
     *
     * @return self
     */
    public function setStatusModificationDate($statusModificationDate)
    {
        if (is_null($statusModificationDate)) {
            array_push($this->openAPINullablesSetToNull, 'statusModificationDate');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('statusModificationDate', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['statusModificationDate'] = $statusModificationDate;

        return $this;
    }

    /**
     * Gets domainId
     *
     * @return int|null
     */
    public function getDomainId()
    {
        return $this->container['domainId'];
    }

    /**
     * Sets domainId
     *
     * @param int|null $domainId Project group ID
     *
     * @return self
     */
    public function setDomainId($domainId)
    {
        if (is_null($domainId)) {
            array_push($this->openAPINullablesSetToNull, 'domainId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('domainId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['domainId'] = $domainId;

        return $this;
    }

    /**
     * Gets clientId
     *
     * @return string|null
     */
    public function getClientId()
    {
        return $this->container['clientId'];
    }

    /**
     * Sets clientId
     *
     * @param string|null $clientId Client ID
     *
     * @return self
     */
    public function setClientId($clientId)
    {
        if (is_null($clientId)) {
            array_push($this->openAPINullablesSetToNull, 'clientId');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('clientId', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['clientId'] = $clientId;

        return $this;
    }

    /**
     * Gets vendors
     *
     * @return \SmartCat\Model\ProjectVendorModel[]|null
     */
    public function getVendors()
    {
        return $this->container['vendors'];
    }

    /**
     * Sets vendors
     *
     * @param \SmartCat\Model\ProjectVendorModel[]|null $vendors Project vendors
     *
     * @return self
     */
    public function setVendors($vendors)
    {
        if (is_null($vendors)) {
            array_push($this->openAPINullablesSetToNull, 'vendors');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('vendors', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['vendors'] = $vendors;

        return $this;
    }

    /**
     * Gets workflowStages
     *
     * @return \SmartCat\Model\ProjectWorkflowStageModel[]|null
     */
    public function getWorkflowStages()
    {
        return $this->container['workflowStages'];
    }

    /**
     * Sets workflowStages
     *
     * @param \SmartCat\Model\ProjectWorkflowStageModel[]|null $workflowStages Project workflow stages
     *
     * @return self
     */
    public function setWorkflowStages($workflowStages)
    {
        if (is_null($workflowStages)) {
            array_push($this->openAPINullablesSetToNull, 'workflowStages');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('workflowStages', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['workflowStages'] = $workflowStages;

        return $this;
    }

    /**
     * Gets documents
     *
     * @return \SmartCat\Model\DocumentModel[]|null
     */
    public function getDocuments()
    {
        return $this->container['documents'];
    }

    /**
     * Sets documents
     *
     * @param \SmartCat\Model\DocumentModel[]|null $documents Project task
     *
     * @return self
     */
    public function setDocuments($documents)
    {
        if (is_null($documents)) {
            array_push($this->openAPINullablesSetToNull, 'documents');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('documents', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['documents'] = $documents;

        return $this;
    }

    /**
     * Gets externalTag
     *
     * @return string|null
     */
    public function getExternalTag()
    {
        return $this->container['externalTag'];
    }

    /**
     * Sets externalTag
     *
     * @param string|null $externalTag External system tag
     *
     * @return self
     */
    public function setExternalTag($externalTag)
    {
        if (is_null($externalTag)) {
            array_push($this->openAPINullablesSetToNull, 'externalTag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('externalTag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['externalTag'] = $externalTag;

        return $this;
    }

    /**
     * Gets specializations
     *
     * @return \SmartCat\Model\Specialization[]|null
     */
    public function getSpecializations()
    {
        return $this->container['specializations'];
    }

    /**
     * Sets specializations
     *
     * @param \SmartCat\Model\Specialization[]|null $specializations Specializations
     *
     * @return self
     */
    public function setSpecializations($specializations)
    {
        if (is_null($specializations)) {
            array_push($this->openAPINullablesSetToNull, 'specializations');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('specializations', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['specializations'] = $specializations;

        return $this;
    }

    /**
     * Gets managers
     *
     * @return string[]|null
     */
    public function getManagers()
    {
        return $this->container['managers'];
    }

    /**
     * Sets managers
     *
     * @param string[]|null $managers Managers
     *
     * @return self
     */
    public function setManagers($managers)
    {
        if (is_null($managers)) {
            array_push($this->openAPINullablesSetToNull, 'managers');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('managers', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['managers'] = $managers;

        return $this;
    }

    /**
     * Gets number
     *
     * @return string|null
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     *
     * @param string|null $number Project number
     *
     * @return self
     */
    public function setNumber($number)
    {
        if (is_null($number)) {
            array_push($this->openAPINullablesSetToNull, 'number');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('number', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets customFields
     *
     * @return array<string,string>|null
     */
    public function getCustomFields()
    {
        return $this->container['customFields'];
    }

    /**
     * Sets customFields
     *
     * @param array<string,string>|null $customFields Custom fields
     *
     * @return self
     */
    public function setCustomFields($customFields)
    {
        if (is_null($customFields)) {
            array_push($this->openAPINullablesSetToNull, 'customFields');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('customFields', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['customFields'] = $customFields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


