<?php
/**
 * RestoreBackupPhase
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;
use \SmartCat\ObjectSerializer;

/**
 * RestoreBackupPhase Class Doc Comment
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RestoreBackupPhase
{
    /**
     * Possible values of this enum
     */
    public const CREATE_PROJECT = 'CreateProject';

    public const IMPORTING_GLOSSARIES = 'ImportingGlossaries';

    public const WAITING_GLOSSARIES = 'WaitingGlossaries';

    public const IMPORTING_TRANSLATION_MEMORIES = 'ImportingTranslationMemories';

    public const WAITING_TRANSLATION_MEMORIES = 'WaitingTranslationMemories';

    public const INSERTING_PARAGRAPHS = 'InsertingParagraphs';

    public const INSERTING_SEGMENTS = 'InsertingSegments';

    public const COMPLETE = 'Complete';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATE_PROJECT,
            self::IMPORTING_GLOSSARIES,
            self::WAITING_GLOSSARIES,
            self::IMPORTING_TRANSLATION_MEMORIES,
            self::WAITING_TRANSLATION_MEMORIES,
            self::INSERTING_PARAGRAPHS,
            self::INSERTING_SEGMENTS,
            self::COMPLETE
        ];
    }
}


