<?php
/**
 * ScopeOfSubstringSearchInProject
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;
use \SmartCat\ObjectSerializer;

/**
 * ScopeOfSubstringSearchInProject Class Doc Comment
 *
 * @category Class
 * @description Scope of sub-string search
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScopeOfSubstringSearchInProject
{
    /**
     * Possible values of this enum
     */
    public const SOURCE = 'Source';

    public const TARGET = 'Target';

    public const CONTEXT = 'Context';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::SOURCE,
            self::TARGET,
            self::CONTEXT
        ];
    }
}


