<?php
/**
 * StatisticsRowModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;

use \ArrayAccess;
use \SmartCat\ObjectSerializer;

/**
 * StatisticsRowModel Class Doc Comment
 *
 * @category Class
 * @description Document Statistics Model
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StatisticsRowModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StatisticsRowModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => '\SmartCat\Model\StatisticsFieldName',
        'words' => 'int',
        'percent' => 'float',
        'segments' => 'int',
        'pages' => 'float',
        'charsWithoutSpaces' => 'int',
        'charsWithSpaces' => 'int',
        'effectiveWordsForBilling' => 'float'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'words' => 'int64',
        'percent' => 'double',
        'segments' => 'int32',
        'pages' => 'double',
        'charsWithoutSpaces' => 'int64',
        'charsWithSpaces' => 'int64',
        'effectiveWordsForBilling' => 'double'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
		'words' => false,
		'percent' => false,
		'segments' => false,
		'pages' => false,
		'charsWithoutSpaces' => false,
		'charsWithSpaces' => false,
		'effectiveWordsForBilling' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'words' => 'words',
        'percent' => 'percent',
        'segments' => 'segments',
        'pages' => 'pages',
        'charsWithoutSpaces' => 'charsWithoutSpaces',
        'charsWithSpaces' => 'charsWithSpaces',
        'effectiveWordsForBilling' => 'effectiveWordsForBilling'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'words' => 'setWords',
        'percent' => 'setPercent',
        'segments' => 'setSegments',
        'pages' => 'setPages',
        'charsWithoutSpaces' => 'setCharsWithoutSpaces',
        'charsWithSpaces' => 'setCharsWithSpaces',
        'effectiveWordsForBilling' => 'setEffectiveWordsForBilling'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'words' => 'getWords',
        'percent' => 'getPercent',
        'segments' => 'getSegments',
        'pages' => 'getPages',
        'charsWithoutSpaces' => 'getCharsWithoutSpaces',
        'charsWithSpaces' => 'getCharsWithSpaces',
        'effectiveWordsForBilling' => 'getEffectiveWordsForBilling'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('words', $data ?? [], null);
        $this->setIfExists('percent', $data ?? [], null);
        $this->setIfExists('segments', $data ?? [], null);
        $this->setIfExists('pages', $data ?? [], null);
        $this->setIfExists('charsWithoutSpaces', $data ?? [], null);
        $this->setIfExists('charsWithSpaces', $data ?? [], null);
        $this->setIfExists('effectiveWordsForBilling', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return \SmartCat\Model\StatisticsFieldName|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param \SmartCat\Model\StatisticsFieldName|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets words
     *
     * @return int|null
     */
    public function getWords()
    {
        return $this->container['words'];
    }

    /**
     * Sets words
     *
     * @param int|null $words Words
     *
     * @return self
     */
    public function setWords($words)
    {
        if (is_null($words)) {
            throw new \InvalidArgumentException('non-nullable words cannot be null');
        }
        $this->container['words'] = $words;

        return $this;
    }

    /**
     * Gets percent
     *
     * @return float|null
     */
    public function getPercent()
    {
        return $this->container['percent'];
    }

    /**
     * Sets percent
     *
     * @param float|null $percent Percent
     *
     * @return self
     */
    public function setPercent($percent)
    {
        if (is_null($percent)) {
            throw new \InvalidArgumentException('non-nullable percent cannot be null');
        }
        $this->container['percent'] = $percent;

        return $this;
    }

    /**
     * Gets segments
     *
     * @return int|null
     */
    public function getSegments()
    {
        return $this->container['segments'];
    }

    /**
     * Sets segments
     *
     * @param int|null $segments Segments
     *
     * @return self
     */
    public function setSegments($segments)
    {
        if (is_null($segments)) {
            throw new \InvalidArgumentException('non-nullable segments cannot be null');
        }
        $this->container['segments'] = $segments;

        return $this;
    }

    /**
     * Gets pages
     *
     * @return float|null
     */
    public function getPages()
    {
        return $this->container['pages'];
    }

    /**
     * Sets pages
     *
     * @param float|null $pages Pages
     *
     * @return self
     */
    public function setPages($pages)
    {
        if (is_null($pages)) {
            throw new \InvalidArgumentException('non-nullable pages cannot be null');
        }
        $this->container['pages'] = $pages;

        return $this;
    }

    /**
     * Gets charsWithoutSpaces
     *
     * @return int|null
     */
    public function getCharsWithoutSpaces()
    {
        return $this->container['charsWithoutSpaces'];
    }

    /**
     * Sets charsWithoutSpaces
     *
     * @param int|null $charsWithoutSpaces Chars Without Spaces
     *
     * @return self
     */
    public function setCharsWithoutSpaces($charsWithoutSpaces)
    {
        if (is_null($charsWithoutSpaces)) {
            throw new \InvalidArgumentException('non-nullable charsWithoutSpaces cannot be null');
        }
        $this->container['charsWithoutSpaces'] = $charsWithoutSpaces;

        return $this;
    }

    /**
     * Gets charsWithSpaces
     *
     * @return int|null
     */
    public function getCharsWithSpaces()
    {
        return $this->container['charsWithSpaces'];
    }

    /**
     * Sets charsWithSpaces
     *
     * @param int|null $charsWithSpaces Chars With Spaces
     *
     * @return self
     */
    public function setCharsWithSpaces($charsWithSpaces)
    {
        if (is_null($charsWithSpaces)) {
            throw new \InvalidArgumentException('non-nullable charsWithSpaces cannot be null');
        }
        $this->container['charsWithSpaces'] = $charsWithSpaces;

        return $this;
    }

    /**
     * Gets effectiveWordsForBilling
     *
     * @return float|null
     */
    public function getEffectiveWordsForBilling()
    {
        return $this->container['effectiveWordsForBilling'];
    }

    /**
     * Sets effectiveWordsForBilling
     *
     * @param float|null $effectiveWordsForBilling Effective word count
     *
     * @return self
     */
    public function setEffectiveWordsForBilling($effectiveWordsForBilling)
    {
        if (is_null($effectiveWordsForBilling)) {
            array_push($this->openAPINullablesSetToNull, 'effectiveWordsForBilling');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('effectiveWordsForBilling', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['effectiveWordsForBilling'] = $effectiveWordsForBilling;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


