<?php
/**
 * WorkUnitType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;
use \SmartCat\ObjectSerializer;

/**
 * WorkUnitType Class Doc Comment
 *
 * @category Class
 * @description Linguist&#39;s work unit
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkUnitType
{
    /**
     * Possible values of this enum
     */
    public const CHAR = 'Char';

    public const WORD = 'Word';

    public const PAGE = 'Page';

    public const HOUR = 'Hour';

    public const MINUTE = 'Minute';

    public const DOCUMENT = 'Document';

    public const SERVICE = 'Service';

    public const DAY = 'Day';

    public const MONTH = 'Month';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CHAR,
            self::WORD,
            self::PAGE,
            self::HOUR,
            self::MINUTE,
            self::DOCUMENT,
            self::SERVICE,
            self::DAY,
            self::MONTH
        ];
    }
}


