<?php
/**
 * WorkflowStageStatus
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Model;
use \SmartCat\ObjectSerializer;

/**
 * WorkflowStageStatus Class Doc Comment
 *
 * @category Class
 * @description Workflow stage status
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkflowStageStatus
{
    /**
     * Possible values of this enum
     */
    public const NOT_ASSIGNED = 'NotAssigned';

    public const ASSIGNED = 'Assigned';

    public const IN_PROGRESS = 'InProgress';

    public const COMPLETED = 'Completed';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_ASSIGNED,
            self::ASSIGNED,
            self::IN_PROGRESS,
            self::COMPLETED
        ];
    }
}


