<?php
/**
 * AuditApi
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SmartCat\ApiException;
use SmartCat\Configuration;
use SmartCat\HeaderSelector;
use SmartCat\ObjectSerializer;

/**
 * AuditApi Class Doc Comment
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AuditApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiIntegrationV1AuditLogsGet' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiIntegrationV1AuditLogsGet
     *
     * Fetch audit logs with given filter parameters
     *
     * @param  \DateTime $startTime Fetch audit logs starting from this date and time (optional)
     * @param  \DateTime $endTime Fetch audit logs until this date and time (optional)
     * @param  int $pageNumber Number of the page. Starts from 1 (optional, default to 1)
     * @param  int $pageSize Size of the page. Available range: 1 - 5000 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1AuditLogsGet'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SmartCat\Model\AuditLogModel[]
     */
    public function apiIntegrationV1AuditLogsGet($startTime = null, $endTime = null, $pageNumber = 1, $pageSize = null, string $contentType = self::contentTypes['apiIntegrationV1AuditLogsGet'][0])
    {
        list($response) = $this->apiIntegrationV1AuditLogsGetWithHttpInfo($startTime, $endTime, $pageNumber, $pageSize, $contentType);
        return $response;
    }

    /**
     * Operation apiIntegrationV1AuditLogsGetWithHttpInfo
     *
     * Fetch audit logs with given filter parameters
     *
     * @param  \DateTime $startTime Fetch audit logs starting from this date and time (optional)
     * @param  \DateTime $endTime Fetch audit logs until this date and time (optional)
     * @param  int $pageNumber Number of the page. Starts from 1 (optional, default to 1)
     * @param  int $pageSize Size of the page. Available range: 1 - 5000 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1AuditLogsGet'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SmartCat\Model\AuditLogModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiIntegrationV1AuditLogsGetWithHttpInfo($startTime = null, $endTime = null, $pageNumber = 1, $pageSize = null, string $contentType = self::contentTypes['apiIntegrationV1AuditLogsGet'][0])
    {
        $request = $this->apiIntegrationV1AuditLogsGetRequest($startTime, $endTime, $pageNumber, $pageSize, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SmartCat\Model\AuditLogModel[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SmartCat\Model\AuditLogModel[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SmartCat\Model\AuditLogModel[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SmartCat\Model\AuditLogModel[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SmartCat\Model\AuditLogModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiIntegrationV1AuditLogsGetAsync
     *
     * Fetch audit logs with given filter parameters
     *
     * @param  \DateTime $startTime Fetch audit logs starting from this date and time (optional)
     * @param  \DateTime $endTime Fetch audit logs until this date and time (optional)
     * @param  int $pageNumber Number of the page. Starts from 1 (optional, default to 1)
     * @param  int $pageSize Size of the page. Available range: 1 - 5000 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1AuditLogsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV1AuditLogsGetAsync($startTime = null, $endTime = null, $pageNumber = 1, $pageSize = null, string $contentType = self::contentTypes['apiIntegrationV1AuditLogsGet'][0])
    {
        return $this->apiIntegrationV1AuditLogsGetAsyncWithHttpInfo($startTime, $endTime, $pageNumber, $pageSize, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiIntegrationV1AuditLogsGetAsyncWithHttpInfo
     *
     * Fetch audit logs with given filter parameters
     *
     * @param  \DateTime $startTime Fetch audit logs starting from this date and time (optional)
     * @param  \DateTime $endTime Fetch audit logs until this date and time (optional)
     * @param  int $pageNumber Number of the page. Starts from 1 (optional, default to 1)
     * @param  int $pageSize Size of the page. Available range: 1 - 5000 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1AuditLogsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV1AuditLogsGetAsyncWithHttpInfo($startTime = null, $endTime = null, $pageNumber = 1, $pageSize = null, string $contentType = self::contentTypes['apiIntegrationV1AuditLogsGet'][0])
    {
        $returnType = '\SmartCat\Model\AuditLogModel[]';
        $request = $this->apiIntegrationV1AuditLogsGetRequest($startTime, $endTime, $pageNumber, $pageSize, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiIntegrationV1AuditLogsGet'
     *
     * @param  \DateTime $startTime Fetch audit logs starting from this date and time (optional)
     * @param  \DateTime $endTime Fetch audit logs until this date and time (optional)
     * @param  int $pageNumber Number of the page. Starts from 1 (optional, default to 1)
     * @param  int $pageSize Size of the page. Available range: 1 - 5000 (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1AuditLogsGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiIntegrationV1AuditLogsGetRequest($startTime = null, $endTime = null, $pageNumber = 1, $pageSize = null, string $contentType = self::contentTypes['apiIntegrationV1AuditLogsGet'][0])
    {



        if ($pageNumber !== null && $pageNumber > 2147483647) {
            throw new \InvalidArgumentException('invalid value for "$pageNumber" when calling AuditApi.apiIntegrationV1AuditLogsGet, must be smaller than or equal to 2147483647.');
        }
        if ($pageNumber !== null && $pageNumber < 1) {
            throw new \InvalidArgumentException('invalid value for "$pageNumber" when calling AuditApi.apiIntegrationV1AuditLogsGet, must be bigger than or equal to 1.');
        }
        
        if ($pageSize !== null && $pageSize > 5000) {
            throw new \InvalidArgumentException('invalid value for "$pageSize" when calling AuditApi.apiIntegrationV1AuditLogsGet, must be smaller than or equal to 5000.');
        }
        if ($pageSize !== null && $pageSize < 1) {
            throw new \InvalidArgumentException('invalid value for "$pageSize" when calling AuditApi.apiIntegrationV1AuditLogsGet, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/api/integration/v1/audit/logs';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $startTime,
            'startTime', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $endTime,
            'endTime', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pageNumber,
            'pageNumber', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $pageSize,
            'pageSize', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
