<?php
/**
 * LspPricesApi
 * PHP version 7.4
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Smartcat API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SmartCat\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use SmartCat\ApiException;
use SmartCat\Configuration;
use SmartCat\HeaderSelector;
use SmartCat\ObjectSerializer;

/**
 * LspPricesApi Class Doc Comment
 *
 * @category Class
 * @package  SmartCat
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LspPricesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'apiIntegrationV1LspPricesPriceIdDelete' => [
            'application/json',
        ],
        'apiIntegrationV2LspPricesBatchGet' => [
            'application/json',
        ],
        'apiIntegrationV2LspPricesBatchPost' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'apiIntegrationV2LspPricesGet' => [
            'application/json',
        ],
        'apiIntegrationV2LspPricesPost' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
        'apiIntegrationV2LspPricesPriceIdPut' => [
            'application/json-patch+json',
            'application/json',
            'text/json',
            'application/*+json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation apiIntegrationV1LspPricesPriceIdDelete
     *
     * Delete an LSP service price
     *
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiIntegrationV1LspPricesPriceIdDelete($priceId, string $contentType = self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'][0])
    {
        $this->apiIntegrationV1LspPricesPriceIdDeleteWithHttpInfo($priceId, $contentType);
    }

    /**
     * Operation apiIntegrationV1LspPricesPriceIdDeleteWithHttpInfo
     *
     * Delete an LSP service price
     *
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiIntegrationV1LspPricesPriceIdDeleteWithHttpInfo($priceId, string $contentType = self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'][0])
    {
        $request = $this->apiIntegrationV1LspPricesPriceIdDeleteRequest($priceId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiIntegrationV1LspPricesPriceIdDeleteAsync
     *
     * Delete an LSP service price
     *
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV1LspPricesPriceIdDeleteAsync($priceId, string $contentType = self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'][0])
    {
        return $this->apiIntegrationV1LspPricesPriceIdDeleteAsyncWithHttpInfo($priceId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiIntegrationV1LspPricesPriceIdDeleteAsyncWithHttpInfo
     *
     * Delete an LSP service price
     *
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV1LspPricesPriceIdDeleteAsyncWithHttpInfo($priceId, string $contentType = self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'][0])
    {
        $returnType = '';
        $request = $this->apiIntegrationV1LspPricesPriceIdDeleteRequest($priceId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiIntegrationV1LspPricesPriceIdDelete'
     *
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiIntegrationV1LspPricesPriceIdDeleteRequest($priceId, string $contentType = self::contentTypes['apiIntegrationV1LspPricesPriceIdDelete'][0])
    {

        // verify the required parameter 'priceId' is set
        if ($priceId === null || (is_array($priceId) && count($priceId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $priceId when calling apiIntegrationV1LspPricesPriceIdDelete'
            );
        }


        $resourcePath = '/api/integration/v1/lsp/prices/{priceId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($priceId !== null) {
            $resourcePath = str_replace(
                '{' . 'priceId' . '}',
                ObjectSerializer::toPathValue($priceId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchGet
     *
     * Fetch LSP service prices
     *
     * @param  string $lastPriceId Fetch the list of service prices starting from the ID that follows the specified ID (optional)
     * @param  int $limit The required number of results (the default is 100) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchGet'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SmartCat\Model\LspPriceModelV2[]
     */
    public function apiIntegrationV2LspPricesBatchGet($lastPriceId = null, $limit = 100, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchGet'][0])
    {
        list($response) = $this->apiIntegrationV2LspPricesBatchGetWithHttpInfo($lastPriceId, $limit, $contentType);
        return $response;
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchGetWithHttpInfo
     *
     * Fetch LSP service prices
     *
     * @param  string $lastPriceId Fetch the list of service prices starting from the ID that follows the specified ID (optional)
     * @param  int $limit The required number of results (the default is 100) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchGet'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SmartCat\Model\LspPriceModelV2[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiIntegrationV2LspPricesBatchGetWithHttpInfo($lastPriceId = null, $limit = 100, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchGet'][0])
    {
        $request = $this->apiIntegrationV2LspPricesBatchGetRequest($lastPriceId, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SmartCat\Model\LspPriceModelV2[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SmartCat\Model\LspPriceModelV2[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SmartCat\Model\LspPriceModelV2[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SmartCat\Model\LspPriceModelV2[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SmartCat\Model\LspPriceModelV2[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchGetAsync
     *
     * Fetch LSP service prices
     *
     * @param  string $lastPriceId Fetch the list of service prices starting from the ID that follows the specified ID (optional)
     * @param  int $limit The required number of results (the default is 100) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesBatchGetAsync($lastPriceId = null, $limit = 100, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchGet'][0])
    {
        return $this->apiIntegrationV2LspPricesBatchGetAsyncWithHttpInfo($lastPriceId, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchGetAsyncWithHttpInfo
     *
     * Fetch LSP service prices
     *
     * @param  string $lastPriceId Fetch the list of service prices starting from the ID that follows the specified ID (optional)
     * @param  int $limit The required number of results (the default is 100) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesBatchGetAsyncWithHttpInfo($lastPriceId = null, $limit = 100, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchGet'][0])
    {
        $returnType = '\SmartCat\Model\LspPriceModelV2[]';
        $request = $this->apiIntegrationV2LspPricesBatchGetRequest($lastPriceId, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiIntegrationV2LspPricesBatchGet'
     *
     * @param  string $lastPriceId Fetch the list of service prices starting from the ID that follows the specified ID (optional)
     * @param  int $limit The required number of results (the default is 100) (optional, default to 100)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiIntegrationV2LspPricesBatchGetRequest($lastPriceId = null, $limit = 100, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchGet'][0])
    {




        $resourcePath = '/api/integration/v2/lsp/prices/batch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $lastPriceId,
            'lastPriceId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchPost
     *
     * Create new LSP service prices
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2[] $lspUpdatePriceModelV2 An array of service price creation requests (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchPost'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SmartCat\Model\AddBatchResult[]
     */
    public function apiIntegrationV2LspPricesBatchPost($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchPost'][0])
    {
        list($response) = $this->apiIntegrationV2LspPricesBatchPostWithHttpInfo($lspUpdatePriceModelV2, $contentType);
        return $response;
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchPostWithHttpInfo
     *
     * Create new LSP service prices
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2[] $lspUpdatePriceModelV2 An array of service price creation requests (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchPost'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SmartCat\Model\AddBatchResult[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiIntegrationV2LspPricesBatchPostWithHttpInfo($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchPost'][0])
    {
        $request = $this->apiIntegrationV2LspPricesBatchPostRequest($lspUpdatePriceModelV2, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SmartCat\Model\AddBatchResult[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SmartCat\Model\AddBatchResult[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SmartCat\Model\AddBatchResult[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SmartCat\Model\AddBatchResult[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SmartCat\Model\AddBatchResult[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchPostAsync
     *
     * Create new LSP service prices
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2[] $lspUpdatePriceModelV2 An array of service price creation requests (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesBatchPostAsync($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchPost'][0])
    {
        return $this->apiIntegrationV2LspPricesBatchPostAsyncWithHttpInfo($lspUpdatePriceModelV2, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiIntegrationV2LspPricesBatchPostAsyncWithHttpInfo
     *
     * Create new LSP service prices
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2[] $lspUpdatePriceModelV2 An array of service price creation requests (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesBatchPostAsyncWithHttpInfo($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchPost'][0])
    {
        $returnType = '\SmartCat\Model\AddBatchResult[]';
        $request = $this->apiIntegrationV2LspPricesBatchPostRequest($lspUpdatePriceModelV2, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiIntegrationV2LspPricesBatchPost'
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2[] $lspUpdatePriceModelV2 An array of service price creation requests (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesBatchPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiIntegrationV2LspPricesBatchPostRequest($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesBatchPost'][0])
    {

        // verify the required parameter 'lspUpdatePriceModelV2' is set
        if ($lspUpdatePriceModelV2 === null || (is_array($lspUpdatePriceModelV2) && count($lspUpdatePriceModelV2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lspUpdatePriceModelV2 when calling apiIntegrationV2LspPricesBatchPost'
            );
        }


        $resourcePath = '/api/integration/v2/lsp/prices/batch';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($lspUpdatePriceModelV2)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($lspUpdatePriceModelV2));
            } else {
                $httpBody = $lspUpdatePriceModelV2;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiIntegrationV2LspPricesGet
     *
     * Fetch LSP service prices by ID
     *
     * @param  string[] $priceIds The list of service price IDs (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesGet'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SmartCat\Model\LspPriceModelV2[]
     */
    public function apiIntegrationV2LspPricesGet($priceIds, string $contentType = self::contentTypes['apiIntegrationV2LspPricesGet'][0])
    {
        list($response) = $this->apiIntegrationV2LspPricesGetWithHttpInfo($priceIds, $contentType);
        return $response;
    }

    /**
     * Operation apiIntegrationV2LspPricesGetWithHttpInfo
     *
     * Fetch LSP service prices by ID
     *
     * @param  string[] $priceIds The list of service price IDs (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesGet'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SmartCat\Model\LspPriceModelV2[], HTTP status code, HTTP response headers (array of strings)
     */
    public function apiIntegrationV2LspPricesGetWithHttpInfo($priceIds, string $contentType = self::contentTypes['apiIntegrationV2LspPricesGet'][0])
    {
        $request = $this->apiIntegrationV2LspPricesGetRequest($priceIds, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\SmartCat\Model\LspPriceModelV2[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SmartCat\Model\LspPriceModelV2[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SmartCat\Model\LspPriceModelV2[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\SmartCat\Model\LspPriceModelV2[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SmartCat\Model\LspPriceModelV2[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiIntegrationV2LspPricesGetAsync
     *
     * Fetch LSP service prices by ID
     *
     * @param  string[] $priceIds The list of service price IDs (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesGetAsync($priceIds, string $contentType = self::contentTypes['apiIntegrationV2LspPricesGet'][0])
    {
        return $this->apiIntegrationV2LspPricesGetAsyncWithHttpInfo($priceIds, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiIntegrationV2LspPricesGetAsyncWithHttpInfo
     *
     * Fetch LSP service prices by ID
     *
     * @param  string[] $priceIds The list of service price IDs (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesGetAsyncWithHttpInfo($priceIds, string $contentType = self::contentTypes['apiIntegrationV2LspPricesGet'][0])
    {
        $returnType = '\SmartCat\Model\LspPriceModelV2[]';
        $request = $this->apiIntegrationV2LspPricesGetRequest($priceIds, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiIntegrationV2LspPricesGet'
     *
     * @param  string[] $priceIds The list of service price IDs (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiIntegrationV2LspPricesGetRequest($priceIds, string $contentType = self::contentTypes['apiIntegrationV2LspPricesGet'][0])
    {

        // verify the required parameter 'priceIds' is set
        if ($priceIds === null || (is_array($priceIds) && count($priceIds) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $priceIds when calling apiIntegrationV2LspPricesGet'
            );
        }


        $resourcePath = '/api/integration/v2/lsp/prices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $priceIds,
            'priceIds', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiIntegrationV2LspPricesPost
     *
     * Create a new LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price creation request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPost'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string
     */
    public function apiIntegrationV2LspPricesPost($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPost'][0])
    {
        list($response) = $this->apiIntegrationV2LspPricesPostWithHttpInfo($lspUpdatePriceModelV2, $contentType);
        return $response;
    }

    /**
     * Operation apiIntegrationV2LspPricesPostWithHttpInfo
     *
     * Create a new LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price creation request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPost'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiIntegrationV2LspPricesPostWithHttpInfo($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPost'][0])
    {
        $request = $this->apiIntegrationV2LspPricesPostRequest($lspUpdatePriceModelV2, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('string' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('string' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation apiIntegrationV2LspPricesPostAsync
     *
     * Create a new LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price creation request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesPostAsync($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPost'][0])
    {
        return $this->apiIntegrationV2LspPricesPostAsyncWithHttpInfo($lspUpdatePriceModelV2, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiIntegrationV2LspPricesPostAsyncWithHttpInfo
     *
     * Create a new LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price creation request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesPostAsyncWithHttpInfo($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPost'][0])
    {
        $returnType = 'string';
        $request = $this->apiIntegrationV2LspPricesPostRequest($lspUpdatePriceModelV2, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiIntegrationV2LspPricesPost'
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price creation request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiIntegrationV2LspPricesPostRequest($lspUpdatePriceModelV2, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPost'][0])
    {

        // verify the required parameter 'lspUpdatePriceModelV2' is set
        if ($lspUpdatePriceModelV2 === null || (is_array($lspUpdatePriceModelV2) && count($lspUpdatePriceModelV2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lspUpdatePriceModelV2 when calling apiIntegrationV2LspPricesPost'
            );
        }


        $resourcePath = '/api/integration/v2/lsp/prices';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['text/plain', 'application/json', 'text/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($lspUpdatePriceModelV2)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($lspUpdatePriceModelV2));
            } else {
                $httpBody = $lspUpdatePriceModelV2;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation apiIntegrationV2LspPricesPriceIdPut
     *
     * Update an existing LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price update request (required)
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function apiIntegrationV2LspPricesPriceIdPut($lspUpdatePriceModelV2, $priceId, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'][0])
    {
        $this->apiIntegrationV2LspPricesPriceIdPutWithHttpInfo($lspUpdatePriceModelV2, $priceId, $contentType);
    }

    /**
     * Operation apiIntegrationV2LspPricesPriceIdPutWithHttpInfo
     *
     * Update an existing LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price update request (required)
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'] to see the possible values for this operation
     *
     * @throws \SmartCat\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function apiIntegrationV2LspPricesPriceIdPutWithHttpInfo($lspUpdatePriceModelV2, $priceId, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'][0])
    {
        $request = $this->apiIntegrationV2LspPricesPriceIdPutRequest($lspUpdatePriceModelV2, $priceId, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation apiIntegrationV2LspPricesPriceIdPutAsync
     *
     * Update an existing LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price update request (required)
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesPriceIdPutAsync($lspUpdatePriceModelV2, $priceId, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'][0])
    {
        return $this->apiIntegrationV2LspPricesPriceIdPutAsyncWithHttpInfo($lspUpdatePriceModelV2, $priceId, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation apiIntegrationV2LspPricesPriceIdPutAsyncWithHttpInfo
     *
     * Update an existing LSP service price
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price update request (required)
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function apiIntegrationV2LspPricesPriceIdPutAsyncWithHttpInfo($lspUpdatePriceModelV2, $priceId, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'][0])
    {
        $returnType = '';
        $request = $this->apiIntegrationV2LspPricesPriceIdPutRequest($lspUpdatePriceModelV2, $priceId, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'apiIntegrationV2LspPricesPriceIdPut'
     *
     * @param  \SmartCat\Model\LspUpdatePriceModelV2 $lspUpdatePriceModelV2 Service price update request (required)
     * @param  string $priceId Service price ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function apiIntegrationV2LspPricesPriceIdPutRequest($lspUpdatePriceModelV2, $priceId, string $contentType = self::contentTypes['apiIntegrationV2LspPricesPriceIdPut'][0])
    {

        // verify the required parameter 'lspUpdatePriceModelV2' is set
        if ($lspUpdatePriceModelV2 === null || (is_array($lspUpdatePriceModelV2) && count($lspUpdatePriceModelV2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $lspUpdatePriceModelV2 when calling apiIntegrationV2LspPricesPriceIdPut'
            );
        }

        // verify the required parameter 'priceId' is set
        if ($priceId === null || (is_array($priceId) && count($priceId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $priceId when calling apiIntegrationV2LspPricesPriceIdPut'
            );
        }


        $resourcePath = '/api/integration/v2/lsp/prices/{priceId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($priceId !== null) {
            $resourcePath = str_replace(
                '{' . 'priceId' . '}',
                ObjectSerializer::toPathValue($priceId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($lspUpdatePriceModelV2)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($lspUpdatePriceModelV2));
            } else {
                $httpBody = $lspUpdatePriceModelV2;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
